### ISSUE TITLE
Default memory requirements are large

### ISSUE THREAD

**Issue by dmc5179** [vmware/safekeeping#7]
The default memory requirements to run safekeeping is 10GB, used right away, and set as the maximum allowed memory usage. I ran the application and the most memory that it used was 4GBs. The memory setting mean that on a small machine with only 8GBs of memory this application cannot be used:

```
$JAVA_HOME/bin/java $DEBUG -ea -server -Xms10G -Xmx10G -server -XX:NewSize=2G  $LIBRARY_PATH_OPTIONS -jar $VMBK_JAR/vmbkcmd.jar $@
```

**Comment by mdaneri** [comment]
you can reduce the memory if you reduce the block size.
inside the config.properties change the property **global.maxBlockSizeMb** 
by default is 250 reduce this number and you can reduce the quantity of required ram.

with version 2.0 I changed this number to 20MB because I'm introducing deduplication and multithreading
